import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";

interface CarImageProps {
  racing: boolean;
  car: number;
  duration: number;
}

export const CarImage: React.FC<CarImageProps> = ({ racing, car, duration }) => {
  const carStyle = racing ? { transform: 'translateX(80vw)', transitionDuration: `${duration}ms`, transitionTimingFunction: 'ease-in-out' } : {};
  return (
    <Image 
      src={`/images/car${car}.gif`}
      width={200} 
      height={200} 
      alt="car" 
      className={`transform transition-transform ${racing ? 'translate-x-[80vw]' : ''}`}
      style={carStyle}
    />
  );
};



export default function Races() {
  const [showCountdown, setShowCountdown] = useState(false);
  const [countdown, setCountdown] = useState(0);


  const [racing, setRacing] = useState(false);

  useEffect(() => {
    if (showCountdown) {
      const interval = setInterval(() => {
        setCountdown((countdown) => countdown > 0 ? countdown - 1 : 0);
        if (countdown === 1) {
          setRacing(true);
          clearInterval(interval);
          setShowCountdown(false);
        }
      }, 1000);
      return () => clearInterval(interval);
    }
  }, [countdown, showCountdown]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-900">
        <h1 className="mt-4 text-center text-2xl text-gray-400">
          Car Racing Game
        </h1>
        <div className="mt-4 flex flex-row justify-center gap-4 text-white">
          <button onClick={() => {
            setCountdown(3);
            setShowCountdown(true)
          }  }
          className="w-36 rounded border border-white px-4 py-1">
            Race!
          </button>
          <button className="w-36 rounded border border-white px-4 py-1">
            Start Over
          </button>
        </div>
        <div className="bg-gray-950">
        <hr className="mt-4 h-2 border-none bg-green-600"></hr>
        <hr className="h-2 border-none bg-white"></hr>
        <CarImage racing={racing} car={1} duration={3500} />
         <hr className="mt-4 h-2 border-none bg-yellow-500"></hr>
        <hr className="mt-2 h-2 border-none bg-yellow-500"></hr>
                <CarImage racing={racing} car={2} duration={2500} />

        <hr className="mt-4 h-2 border-none bg-white"></hr>
        <hr className="h-2 border-none bg-green-600 "></hr>
        </div>

        <div className="flex flex-row justify-center">
          <p className="mt-6 text-left text-3xl text-gray-400">Results</p>
        </div>

        {showCountdown && (
          <div className="absolute top-0 left-0 w-full h-full bg-black bg-opacity-50">
            <p className="fixed left-1/2 top-1/2 
            -translate-x-1/2 -translate-y-1/2 text-white font-bold 
            text-8xl">{countdown}</p>
          </div>
        )}
      </main>
    </>
  );
}
